import type { CarList } from "../types/CarList";

const carList: Array<CarList> = [
  {
    id: 1,
    brand: "bmw serie 3",
    year: "2020",
    doors: 4,
    transmission: "automatico",
    price: 40000,
    color: "negro",
  },
  {
    id: 2,
    brand: "audi a4",
    year: "2020",
    doors: 4,
    transmission: "automatico",
    price: 30000,
    color: "blanco",
  },
  {
    id: 3,
    brand: "ford mustang",
    year: "2015",
    doors: 2,
    transmission: "automatico",
    price: 20000,
    color: "blanco",
  },
  {
    id: 4,
    brand: "audi a6",
    year: "2019",
    doors: 4,
    transmission: "manual",
    price: 35000,
    color: "azul",
  },
  {
    id: 5,
    brand: "bmw serie 5",
    year: "2016",
    doors: 4,
    transmission: "manual",
    price: 70000,
    color: "blanco",
  },
  {
    id: 6,
    brand: "mercedez bens clase c",
    year: "2015",
    doors: 4,
    transmission: "automatico",
    price: 25000,
    color: "negro",
  },
  {
    id: 7,
    brand: "chevrolet camaro",
    year: "2018",
    doors: 2,
    transmission: "automatico",
    price: 40000,
    color: "blanco",
  },
  {
    id: 8,
    brand: "ford mustang",
    year: "2019",
    doors: 2,
    transmission: "manual",
    price: 80000,
    color: "rojo",
  },
  {
    id: 9,
    brand: "ford mustang",
    year: "2019",
    doors: 2,
    transmission: "manual",
    price: 60000,
    color: "amarillo",
  },
  {
    id: 10,
    brand: "dodge challenger",
    year: "2013",
    doors: 4,
    transmission: "automatico",
    price: 45000,
    color: "violeta",
  },
  {
    id: 11,
    brand: "audi a3",
    year: "2017",
    doors: 4,
    transmission: "manual",
    price: 35000,
    color: "rojo",
  },
  {
    id: 12,
    brand: "dodge challenger",
    year: "2015",
    doors: 2,
    transmission: "automatico",
    price: 30000,
    color: "azul",
  },
  {
    id: 13,
    brand: "mercedez bens",
    year: "2012",
    doors: 4,
    transmission: "manual",
    price: 55000,
    color: "verde",
  },
  {
    id: 14,
    brand: "bmw series 5",
    year: "2011",
    doors: 4,
    transmission: "automatico",
    price: 40000,
    color: "violeta",
  },
  {
    id: 15,
    brand: "ford mustang",
    year: "2014",
    doors: 4,
    transmission: "manual",
    price: 35000,
    color: "azul",
  },
  {
    id: 16,
    brand: "dodge challenger",
    year: "2010",
    doors: 4,
    transmission: "automatico",
    price: 25000,
    color: "verde",
  },
  {
    id: 17,
    brand: "dodge challenger",
    year: "2013",
    doors: 4,
    transmission: "manual",
    price: 70000,
    color: "rojo",
  },
  {
    id: 18,
    brand: "ford mustang",
    year: "2012",
    doors: 2,
    transmission: "manual",
    price: 20000,
    color: "negro",
  },
  {
    id: 19,
    brand: "mercedez bens clase c",
    year: "2016",
    doors: 4,
    transmission: "automatico",
    price: 30000,
    color: "blanco",
  },
  {
    id: 20,
    brand: "audi a4",
    year: "2018",
    doors: 4,
    transmission: "manual",
    price: 45000,
    color: "rojo",
  },
  {
    id: 21,
    brand: "bmw serie 6",
    year: "2019",
    doors: 4,
    transmission: "automatico",
    price: 80000,
    color: "gris",
  },
];

export default carList;
